name: ci

on: [push, pull_request]

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  deno:
    name: ci
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'denoland:')
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5

      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      - name: install
        run: deno install

      - name: fmt
        run: deno fmt --check

      - name: lint
        run: deno lint

      - name: test
        run: deno test -P
